name: my_personal_website
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0-198.0.dev

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.7.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  build_web_compilers: ^4.1.1
  url_launcher: ^6.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/
